import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="bg-gradient-to-r from-slate-400 to-teal-600 h-40">Meu teste</div>
			<h1 className="text-5xl text-center text-lime-800">Hello World</h1>
		</div>
	);
}
